# Generated by Django 5.1.2 on 2026-03-27 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('display_name', models.CharField(blank=True, help_text='Public display name', max_length=100)),
                ('bio', models.TextField(blank=True, help_text='Short biography', max_length=500)),
                ('avatar', models.ImageField(blank=True, help_text='Profile picture (JPEG/PNG/WebP, max 5MB)', null=True, upload_to='avatars/')),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, help_text='Birth date', null=True)),
                ('preferences', models.JSONField(blank=True, default=dict, help_text='User preferences and settings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
        ),
    ]
