# Generated by Django 5.1.2 on 2026-03-27 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique policy identifier', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Human-readable description of the policy')),
                ('conditions', models.JSONField(blank=True, default=dict, help_text='Rule conditions (time_window, ip_whitelist, etc.)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this policy is currently enforced')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'policy',
                'verbose_name_plural': 'policies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GroupPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(help_text='The role this policy applies to', on_delete=django.db.models.deletion.CASCADE, related_name='group_policies', to='auth.group')),
                ('policy', models.ForeignKey(help_text='The policy assigned to the role', on_delete=django.db.models.deletion.CASCADE, related_name='group_policies', to='profiles.policy')),
            ],
            options={
                'verbose_name': 'group policy',
                'verbose_name_plural': 'group policies',
                'ordering': ['group__name', 'policy__name'],
                'unique_together': {('group', 'policy')},
            },
        ),
    ]
