# Generated by Django 5.1.2 on 2026-03-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_add_policy_and_grouppolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age_verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('self_declared', 'Self Declared'), ('pending', 'Pending Verification'), ('verified', 'Verified'), ('failed', 'Verification Failed')], default='unverified', help_text='Current age verification state', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='age_verified_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last verification status change', null=True),
        ),
    ]
