# Generated by Django 5.1.2 on 2026-03-28 00:34

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_add_age_verification_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Birth date', null=True, validators=[profiles.models.validate_date_of_birth_not_future, profiles.models.validate_date_of_birth_not_too_old]),
        ),
    ]
