# Generated by Django 5.1.2 on 2026-03-27 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_email_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebAuthnCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_id', models.BinaryField(help_text='WebAuthn credential identifier (opaque bytes from authenticator).', max_length=1024, unique=True)),
                ('public_key', models.BinaryField(help_text='COSE-encoded public key for signature verification.', max_length=1024)),
                ('sign_count', models.PositiveIntegerField(default=0, help_text='Signature counter for cloning detection.')),
                ('webauthn_user_id', models.BinaryField(help_text='Random user handle used during registration (NOT the DB PK).', max_length=64)),
                ('device_label', models.CharField(blank=True, default='', help_text='User-provided or auto-generated device label.', max_length=100)),
                ('is_enabled', models.BooleanField(default=True, help_text='False when disabled (e.g., cloning detected).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webauthn_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WebAuthn credential',
                'verbose_name_plural': 'WebAuthn credentials',
                'indexes': [models.Index(fields=['user', 'is_enabled'], name='users_webau_user_id_02170f_idx')],
            },
        ),
    ]
