# Generated by Django 5.1.2 on 2026-03-28 02:23

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_add_webauthn_credential"),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, db_index=True, help_text='Account username. User-supplied values must match project username rules; legacy rows may be backfilled from email.', max_length=255, null=True, verbose_name='username'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='username_changed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the username was last changed by the user.', null=True, verbose_name='username changed at'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(django.db.models.functions.text.Lower('username'), name='users_custom_username_ci_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['username_changed_at'], name='users_custo_usernam_76fc0c_idx'),
        ),
    ]
