# Generated by Django 5.1.2 on 2026-04-27 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Public event title.', max_length=255)),
                ('description', models.TextField(help_text='Public event description.', max_length=1000)),
                ('category', models.CharField(choices=[('music', 'Music'), ('food_drink', 'Food & Drink'), ('arts_culture', 'Arts & Culture'), ('community', 'Community'), ('sports_fitness', 'Sports & Fitness'), ('business_networking', 'Business & Networking'), ('education_workshop', 'Education & Workshop'), ('other', 'Other')], default='other', help_text='Primary event category.', max_length=32)),
                ('start_at', models.DateTimeField(help_text='Scheduled event start date and time.')),
                ('end_at', models.DateTimeField(help_text='Scheduled event end date and time.')),
                ('location_type', models.CharField(choices=[('physical', 'Physical'), ('web', 'Web')], help_text='Whether the event uses a physical or web location.', max_length=16)),
                ('location_web_url', models.URLField(blank=True, help_text='Web address for online events.', max_length=500, null=True)),
                ('location_country', models.CharField(blank=True, help_text='Country for physical event locations.', max_length=100, null=True)),
                ('location_state', models.CharField(blank=True, help_text='State or region for physical event locations.', max_length=100, null=True)),
                ('location_city', models.CharField(blank=True, help_text='City or town for physical event locations.', max_length=100, null=True)),
                ('location_postcode', models.CharField(blank=True, help_text='Postcode or zipcode for physical event locations.', max_length=32, null=True)),
                ('cover_image', models.ImageField(blank=True, help_text='Optional event cover image.', null=True, upload_to='events/covers/')),
                ('tickets_url', models.URLField(blank=True, help_text='Optional tickets or registration link.', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, help_text='Organization that owns this event when not personal.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='organizations.organization')),
                ('owner', models.ForeignKey(blank=True, help_text='User who owns this personal event.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
                'ordering': ['-created_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='EventAuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(choices=[('title', 'Title'), ('start_at', 'Start Time'), ('end_at', 'End Time'), ('location', 'Location')], help_text='Tracked event field that changed.', max_length=16)),
                ('old_value', models.TextField(help_text='Previous normalized value for the tracked field.')),
                ('new_value', models.TextField(help_text='New normalized value for the tracked field.')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(help_text='User who made the tracked event change.', on_delete=django.db.models.deletion.CASCADE, related_name='event_audit_entries', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(help_text='Event whose tracked field changed.', on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='events.event')),
            ],
            options={
                'verbose_name': 'event audit entry',
                'verbose_name_plural': 'event audit entries',
                'ordering': ['-changed_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['owner', '-created_at'], name='events_even_owner_i_cd92aa_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organization', '-created_at'], name='events_even_organiz_747bab_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['category', 'start_at'], name='events_even_categor_f39b94_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['location_type', 'start_at'], name='events_even_locatio_c66a5d_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['created_at'], name='events_even_created_52c227_idx'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('organization__isnull', True), ('owner__isnull', False)), models.Q(('organization__isnull', False), ('owner__isnull', True)), _connector='OR'), name='events_event_exactly_one_owner'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('end_at__gt', models.F('start_at'))), name='events_event_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='eventauditentry',
            index=models.Index(fields=['event', '-changed_at'], name='events_even_event_i_9b5469_idx'),
        ),
        migrations.AddIndex(
            model_name='eventauditentry',
            index=models.Index(fields=['actor', '-changed_at'], name='events_even_actor_i_d8e4c7_idx'),
        ),
        migrations.AddIndex(
            model_name='eventauditentry',
            index=models.Index(fields=['field_name', '-changed_at'], name='events_even_field_n_c40fa5_idx'),
        ),
    ]
