# Generated by Django 5.1.2 on 2026-04-26 12:41

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Public organization name.', max_length=255)),
                ('description', models.TextField(help_text='Public organization description or bio.')),
                ('organization_type', models.CharField(choices=[('restaurant', 'Restaurant'), ('barber', 'Barber'), ('hair_salon', 'Hair Salon'), ('bar', 'Bar'), ('night_club', 'Night Club'), ('event_organizer', 'Event Organizer'), ('dance_crew', 'Dance Crew'), ('online_community', 'Online Community'), ('retail_store', 'Retail Store'), ('other', 'Other')], help_text='Primary organization category.', max_length=32)),
                ('is_online_only', models.BooleanField(default=False, help_text='Whether the organization operates online without a storefront.')),
                ('physical_address', models.TextField(blank=True, help_text='Physical organization address when not online-only.', null=True)),
                ('logo', models.ImageField(blank=True, help_text='Optional organization logo.', null=True, upload_to='organizations/logos/')),
                ('cover_image', models.ImageField(blank=True, help_text='Optional organization cover image.', null=True, upload_to='organizations/covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='User who manages this organization profile.', on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organizations',
                'ordering': ['-created_at', 'name'],
                'indexes': [models.Index(fields=['owner', '-created_at'], name='organizatio_owner_i_28d448_idx'), models.Index(fields=['organization_type', 'is_online_only'], name='organizatio_organiz_3a1424_idx'), models.Index(fields=['created_at'], name='organizatio_created_dfd536_idx')],
                'constraints': [models.UniqueConstraint(models.F('owner'), django.db.models.functions.text.Lower('name'), name='organizations_org_owner_name_ci_uniq')],
            },
        ),
    ]
